# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zhifeng Liu
email: zhifengliu@stu.pku.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  Zhifeng Liu's personal website.
twitter_username: 
github_username: 
minimal_mistakes_skin: contrast
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XTHT47L5JM"
    anonymize_ip: false # default

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Zhifeng Liu"
  avatar : "https://avatars.githubusercontent.com/u/34160072?s=400&u=565ddef6c8cbf38b04e6714b7664db3d9d84af63&v=4"
  bio    : "I am Zhifeng Liu, a phd student at the Department of Information Management, Peking University."
  location: "Beijing, China"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "zhifengliu@stu.pku.edu.cn"
    - label: "Pku Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.pku.edu.cn/"
    - label: "Researchgate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Zhifeng-Liu-14"
     

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "zhifengliu@stu.pku.edu.cn"  


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
